### ISSUE TITLE
How to instantiate multiple instances of an extension

### ISSUE THREAD

**Issue by nonnamon** [pf4j/pf4j#215]
What would be the correct way to instantiate more than one instance of a plugins extension?

**Comment by decebals** [comment]
Can you add more details (eventually some code)?

**Comment by nonnamon** [comment]
>  an extension point (an interface with one single method calculateScore(int dbkey)).

correct

> Have you multiple plugins, each plugin contains an extension, or only a plugin that contains multiple extensions?

Multiple plugins, each containing an extension point implementing _calculateScore(int dbkey)_

So each plugin+extension point implements a different algorithm for calculating a score. For one plugin+extension it can be used to _calculateScore_ over separate data / sections of database. 

I can't provide actual code atm, but a contrived example: currently something like the following can be done sequentially:

```
interface IScoreFunction { 
  int getId(); 
  int calculateScore(int from);
}
...
functions = pluginmanager.getExtensions(AbstractScoreFunction.class)
...
if ( func.getId() == AlgorithmXyz )
 for ( int startPoint = 0; startPoint < 10; startPoint+=100) {
    func.calcScore(startPoint);
  }
}
```
So instead of, as above, using one _func_ instance to sequentially call _func.calcScore()_ it would be preferable to create & execute multiple instances of AlgorithmXyz extension in separate threads.

Does that clarify?

**Comment by decebals** [comment]
Now, I understand what you try to achieve. Thanks for the detailed explanation.
I think that you can use [PluginManager#getExtensionClasses(Class<T> type)](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/PluginManager.java#L134) instead of `PluginManager#getExtensions(Class<T> type)`, and to use [ExtensionFactory#getExtensionFactory()](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/PluginManager.java#L146) to create extensions instances via [ExtensionFactory#create(Class<?> extensionClass)](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/ExtensionFactory.java#L23).

Does it make sense to you what I say?

**Comment by nonnamon** [comment]
yes i think so. i did start looking at getExtensionClasses(Class type) but ran into some confusion, i will take a closer look.

**Comment by nonnamon** [comment]
That seemed to work, thank you.
