### ISSUE TITLE
Suggestion: Change application required version

### ISSUE THREAD

**Issue by ykrasik** [pf4j/pf4j#280]
I think the current implementation of a plugin requiring a certain application version doesn't cover an important use case - an application with multiple plugin types, or multiple plugin apis. Specifically I'm referring to a case where the application is updated to a newer version, but the plugins remain the old version. This can happen when the update channels for the application & plugins are separate.
Let's assume we have an application v `1.0.0` with 2 separate extension interfaces - `ExtensionA` & `ExtensionB`. Let's look at a few scenarios:

- The plugins that provide these extension require an application version of `1.0.0` exactly. 
  - When we upgrade the application to `2.0.0` (without upgrading the plugins), these plugins are no longer considered compatible and the user has to update his plugins, even though it's possible that the breaking change that caused the major bump in the application had nothing to do with the code that runs these plugins and this situation could be avoided.
- The plugins that provide these extension require an application version of >= `1.0.0`.
  - When we upgrade the application to `2.0.0` (without upgrading the plugins), these plugins are still considered compatible even though it's possible that the code that runs them changed in a breaking manner, resulting in runtime errors.

This situation can be avoided by a more granular definition of version requirements. My suggestion is this: 
Instead of requiring an application version by the plugin, the plugins declare the version of application APIs they use. If a plugin relies on code that belongs to 2 APIs of the application to function properly, it would list it in the manifest (or properties). More concretely, it would look something like this:
```
Plugin-Application-Api: ExtensionAApi:1.0.0
Plugin-Application-Api: ExtensionBApi:2.1.1
```
The above code declares that in order to function correctly, the plugin must interface with an application with an `ExtensionAApi` api of `1.0.0` (or higher minor version) & an api of `ExtensionBApi` of `2.1.1` (or higher minor version) .
The application knows what version of these APIs it currently has (it keeps this information somewhere and lets the PluginManager know about it). When plugins are loaded, it compares their declared versions with the application's provided versions, and only allows plugins that are compatible with all APIs it relies on. Plugins are only compatible if they are of the same major API version.
This will allow bumping the major version of an application but still allowing potentially compatible old plugins to run (if the APIs it relies on didn't change) and also take away the guesswork of defining which application version the plugin is compatible with.

**Comment by decebals** [comment]
I prefer to keep things simple and complex/uncommon use cases to be possible to implement them.
In many situation is enough to create your custom `PluginManager` that could extends `DefaultPluginManager` or `AbstractPluginManager` and to override some methods (factory methods or not). Maybe the solution to your problem is to override [AbstractPluginManager.isPluginValid](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/AbstractPluginManager.java#L750).
An interesting idea is to have a possibility to use an Extended/Custom `PluginDescriptor` in PF4J. In this mode you can create your custom `PluginDescriptor` (with a new `Plugin-Application-Api` attribute), override [AbstractPluginManager.validatePluginDescriptor](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/AbstractPluginManager.java#L898) if your new plugin descriptor attribute(s) is(are) mandatory and override [AbstractPluginManager.isPluginValid](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/AbstractPluginManager.java#L750) if you have a specific business.

**Comment by ykrasik** [comment]
Interesting, I will look into it. Thanks!
