### ISSUE TITLE
Configure compound classes to use JAR plugins first

### ISSUE THREAD

**Issue by dmitry-timofeev** [pf4j/pf4j#294]
As documentation states that the JAR plugin format is recommended and shall be used by default, shan't the compound description finder, loader, and repository be configured with JAR versions first? It will (can't say how much) improve performance and reduce the number of log messages in the common case.

**Comment by decebals** [comment]
The first plugin format supported by PF4J was ZIP. In order to not affect the applications that already use this format (old PF4J version) for plugins, and to increase the adoption of the new PF4J versions, I made the decision to support this format out of the box (no modifications required).
If other users/developers vote to support only JAR plugins by default (and to specify implicitly when the application uses ZIP format for plugins) we can made the modifications.

**Comment by dmitry-timofeev** [comment]
I see, thanks! Such change is breaking for the applications using _both_ formats and relying on CompondX to pick the right format. But just to be clear: I do not propose to drop support of ZIP; rather to check for JAR in CompoundX managers _first_ because JAR is the default format.

**Comment by decebals** [comment]
> rather to check for JAR in CompoundX managers first because JAR is the default format.

Thanks for clarification. I think that is a good idea. A PR is welcome.

**Comment by decebals** [comment]
I made the modifications on a new (feature) branch. I was forced to adapt a test to fix a fail. This test fail can be a problem for people, so I will investigate why the test failed:

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at org.pf4j.LoadPluginsTest.deletePlugin(LoadPluginsTest.java:243)
```

![image](https://user-images.githubusercontent.com/1248311/54226408-76659580-4506-11e9-936e-45939971eb39.png)
