### ISSUE TITLE
Create specific implementations of PluginManager

### ISSUE THREAD

**Issue by decebals** [pf4j/pf4j#307]
The `PluginManager` is the entry point in PF4J. So, first step when you use PF4J in your application is to choose a `PluginManager` implementation.
The current options are:
- `DefaultPluginManager` (most common cases)
- create your custom `PluginManager` implementation extending `DefaultPluginManager`
- create your custom `PluginManager` implementation extending `AbstractPluginManager` (it contains few abstract methods that must be implemented by you)
- create your custom `PluginManager` implementation from scratch (implement all methods from `PluginManger`)

I think that would be useful to add two new `PluginManager` implementations:
- `JarPluginManager`
- `ZipPluginManager`

Both new plugin managers would extend `DefaultPluginManager` and will override `createPluginLoader` and `createPluginDescriptorFinder`. The code for both new classes is trivial.

What do you think? would it be useful?

**Comment by pinhead84** [comment]
I like the idea of having separate implementations of `PluginManager`. For those common cases other developers won't have to implement their own `AbstractPluginManager`. Also I like this because it better documents the different implementations for new users.

For the sake of documentation a `DevelopmentPluginManager`, which makes use of `DevelopmentPluginClasspath` (see [here](https://github.com/pf4j/pf4j/blob/3d6233154f44806b95dd4bf01e8264889492a082/pf4j/src/main/java/org/pf4j/DefaultPluginManager.java#L114)), might also make sense.

**Comment by dmitry-timofeev** [comment]
I think it would be useful to have library-provided versions of such plugin managers, partly for the reasons described in #294, and also because a more specific and simple JarPluginManager is probably all users need. If someone needs a pm that supports several formats at once, they could opt-in and use `DefaultPluginManager`.

We, for instance, stripped-down the DefaultPluginManager to [support JARs only](https://github.com/exonum/exonum-java-binding/pull/793/files#diff-efc93408e4c121c2b33721baf31ec1d9R32).

**Comment by decebals** [comment]
With https://github.com/pf4j/pf4j/commit/ce4c79380398d0c2280f784cd523dfe31026d671 I added a first version for `JarPluginManager` and `ZipPluginManager`. For the moment the unit test are missing.

Other thing that is missing is the part with `DevelopmentPluginClasspath`.
In my projects I don't care about the final pack format of plugins (zip, jar). This is a detail for me and my development team that works on that project.
We use a project structure similar with [demo] (https://github.com/pf4j/pf4j/tree/master/demo) (with `api`, `app` and `plugins` as modules). All the application's plugins developed by us are under `plugins` directory (this directory is the root of all plugins). So, without any modifications we run the entire application, with all the plugins, from our IDE, such a simple `Hello World` application. I would like to keep this easy and very productive mechanism in the future.

**Comment by decebals** [comment]
`DevelopmentPluginManager` remaining. Or find an elegant solution how to integrate this component (`DevelopmentPluginClasspath`) in the new plugin manager implementations.

**Comment by decebals** [comment]
I added support for `development` mode for the new `PluginManager`s (`JarPluginManager` and `ZipPluginManager`). I rethinked the part with `PluginRepository` and `PluginLoader` (added concrete implementations for development mode) and I believe that the final result is a progress (the concepts are more clear).
I think that now this feature is complete implemented.
