### ISSUE TITLE
Migrate JPF to PF4J

### ISSUE THREAD

**Issue by zc0nf** [pf4j/pf4j#343]
Hello!

Does anyone have a procedure or other to migrate from [JPF](http://jpf.sourceforge.net/) to PF4J?

Thank you!

**Comment by decebals** [comment]
If nobody converted a JPF to PF4J maybe it's time to start to work on this subject. I don't know to much about JPF but I will try to read the documentation and to compare with what already exist in PF4J.
First of all I think that they are some concepts that exist in both projects:
- plugin
- extension point
- extension

but each project has a different mode to declare these components.

In JPF, you have a `plugin.xml` where you declare the plugin metadata (name/id, class, version, ...). In PF4J you can do it in multiple modes. The buit-in modes are:
- `plugin.properties`
- `MANIFEST.MF` (jar)

Each project has a `PluginManager` concept that it's the entry point for your application. Here, you can `start`, `stop`, `destroy` plugins.

I see also that JPF uses a different `ClassLoader` for each plugin.

JPF uses a lot of [xml](http://jpf.sourceforge.net/dtd.html) to declare the plugin metadata, extensions points and extensions. Instead, PF4J uses only plain Java to declare these components (see `Extension` annotation and `ExtensionPoint` interface marker).

In the end I think, after I read about JPF, that it's not so complicate to convert an application based on JPF in an application based on PF4J.
The first steps are to migrate plugins, extensions points and extensions from JPF (XML - plugin.xml) to PF4J (plain Java).

@zc0nf 
I propose you to start with a small prototype (if your project it's big). Share this prototype with us (GitHub project) and when you encounter problems, leave here a comment that describe your problem.

**Comment by zc0nf** [comment]
Thx decebals,

Our project : 
[https://github.com/drftpd-ng/drftpd3]

Currently it only works with java 8 because of jpf. The implementation uses 1 wrapper parameter that is deprecated (wrapper and slave.conf):
`XX: + UnsyncloadClass`

The boot uses the following parameters:

```
# $Id$
#-------------------------------------------------------------------------------
# DRFTPD Master application plug-in ID
org.java.plugin.boot.applicationPlugin = master
# Boot-time integrity check mode (full, light, off)
org.java.plugin.boot.integrityCheckMode = full
org.java.plugin.boot.errorHandler = org.java.plugin.boot.BootErrorHandlerConsole
org.java.plugin.boot.pluginsRepositories = ./core,./plugins/common,./plugins/master
#-------------------------------------------------------------------------------
# JPF runtime configuration
org.java.plugin.standard.PluginLifecycleHandler = org.java.plugin.drftpd.SynchronizedPluginLifecycleHandler
org.java.plugin.PathResolver = org.java.plugin.standard.ShadingPathResolver
org.java.plugin.standard.ShadingPathResolver.shadowFolder = .jpf_shadow
#-------------------------------------------------------------------------------
```

jpf fork exists but no longer supported : 

[https://github.com/openequella/openEQUELLA-jpf/commits/master]

jpf demo exists too : 

[https://sourceforge.net/projects/jpf/files/jpf-demo-1.5/jpf-demo-1.5.0/}

Our goal to make the project live and that it is beneficial to the community, is to migrate the current plugins framework to pf4j except that we are sorely lacking in this domain, the understanding of jpf is complex at our level and we do not know anyone who knows how to maintain this framework or even evolve it to be compatible with plugins for java11+.

**Comment by decebals** [comment]
> the understanding of JPF is complex at our level and we do not know anyone who knows how to maintain this framework or even evolve it to be compatible with plugins for Java11+.

I think that it's not so complex (at least that's how I see it). Unfortunately I don't have time to investigate your project. I can help you only with some answers to punctual questions.

**Comment by zc0nf** [comment]
Hi @pinhead84,

Can you help us better understand migration?

Thanks a lot you two.

zc0nf

**Comment by decebals** [comment]
@pinhead84 
I think that @zc0nf talks about:

![image](https://user-images.githubusercontent.com/1248311/68234096-3ad58980-0009-11ea-8f67-e6d81d15f3a1.png)

![image](https://user-images.githubusercontent.com/1248311/68234226-6fe1dc00-0009-11ea-80d9-cf4227c51140.png)

**Comment by pinhead84** [comment]
Hi @zc0nf,

as @decebals already pointed out, PF4J is pretty similar to JPF in its basic concepts. From my point of view it's a big advantage, that you don't need these annoying `plugin.xml` files anymore. 

- Instead of defining the extension points [there](https://github.com/drftpd-ng/drftpd3/blob/master/src/master/plugin.xml), you just create classes / interfaces with an `@ExtensionPoint` annotation [as described here](https://pf4j.org/doc/extensions.html).

- The plugins itself are classes derived from the `org.pf4j.Plugin` base class [as described here](https://pf4j.org/doc/plugins.html).

- While compiling the plugin the compiler will automatically detect all available classes with an `@ExtensionPoint` annotation for you. This makes the whole process of defining extension points much easier and less faulty.

A bigger difference compared to JPF is, that you don't need an application plugin derived from from `org.java.plugin.boot.ApplicationPlugin` or the application interface `org.java.plugin.boot.Application`. Just create a simple Java class with a static `main(String[] args)` method and initialize the plugin enviromnent [as described here](https://pf4j.org/doc/getting-started.html). Also the separate `jpf-boot` library is not necessary with PF4J anymore. Just start your application through the `main(String[] args)` method.

The whole migration process is more or less straightforward, but I highly recommend, that you take a look into the [documentation](https://pf4j.org/), create a little test application and play around with PF4J before migrating your whole application.

The application I've migrated was also pretty complex with a lot of extension points and inner plugin dependencies. But after @decebals accepted some improvements, I believe, that PF4J covers all features from JPF. Most JPF based application should also work with PF4J without making too many changes.

I wish you best luck with the migration process. In case of general questions feel free to ask.

**Comment by zc0nf** [comment]
Thank you very much,

We must now find developers understand what you just explained (I'm not a developer) and it's quite complicated on this part!

I do not know if this issue remains open or not?

zc0nf

**Comment by decebals** [comment]
@zc0nf 
I will close this issue. if you have specific questions please reopen the issue.
