### ISSUE TITLE
extending non extension points and configuration

### ISSUE THREAD

**Issue by claymccoy** [pf4j/pf4j#358]
I've used #350 to extend an interface that I didn't have direct control over and it worked well. But the constraint that my extension has a single interface is quite limiting. There are definitely cases where I would want to:
* extend a class or abstract class
* require multiple interfaces on my extension point

I'll describe one case in particular. We are using pf4j in Spinnaker. My extension requires bringing in config values from a config file. We have added some code in Spinnaker that can inject the config into the extension, but it requires on to use the [ConfigurableExtension interface](https://github.com/spinnaker/kork/blob/dbbdaf1eb4602884f6216ef569b1f734257d5caa/kork-plugins-api/src/main/java/com/netflix/spinnaker/kork/plugins/ConfigurableExtension.java). This is fine, unless you are trying to use the "extend interface" feature where you can only have one interface. My interface for the extension point is a second interface. A workaround for this is to make an abstract class that brings in ConfigurableExtension and use that as a supertype for my extension. But this is not ideal.
I have two takeaways from this:
1) Should p4fj have native support for configuring extensions? It feels like this is pretty common and it would have kept us from having ConfigurableExtension in the first place. I don't need pf4j to actually read the properties (that is app specific so it should at least be extensible) but it would be nice to have a pf4j core way to hand the properties to an extension. Maybe this could be an annotation on a method that removes the need to complicate the class hierarchy?
2) I understand how limiting my extension to a single interface makes it simple to implicitly figure out the extension point. But it would be much more useful if it didn't limit me to one interface.
3) Is it possible for an extension to subclass a class or an abstract class and use that as an extension point. It isn't always interfaces that we want to extend.

**Comment by claymccoy** [comment]
There is some discussion here #289 about what ExtensionPoint means anymore in a world where you can define an extension to things that aren't extension points.
Ideally, I would have a marker annotation for extension points in my app, just to document and find the places that are designed to be extended, and also explicitly configure plugins that are capable of extending nonextension points (expert mode). This is really all that I see as valuable.
It would be nice if `Extension` was not in pf4j core because it forces me to bring it all into my plugin. I'd prefer there to be a pf4j-api with minimal dependencies.
I'd also prefer to be able to define my own marker annotation in my app rather than having to use `ExtensionPoint`.

**Comment by claymccoy** [comment]
I just noticed [Extension.points](https://github.com/pf4j/pf4j/blob/f6ebda434d51a6e9708e6612f422eb88420ff99d/pf4j/src/main/java/org/pf4j/Extension.java#L48).
If this allowed me to specify my own interfaces (and even classes) to extend instead of having to supply a single interface it would work great. Unfortunately, it has to reference an ExtensionPoint. :(
I don't understand the case for this to be multiple extension points defined.

**Comment by decebals** [comment]
I will try to answer you to your questions. 
You have put in your comments a lot of information that is very good, but at the same time it makes it difficult for me to answer all your questions :).

> Should p4fj have native support for configuring extensions?

I think that it will be interesting but for the moment I don't know how to pack this new concept in a simple, non intrusive and optional form.
We can try something (POC) on a feature branch.

> I understand how limiting my extension to a single interface makes it simple to implicitly figure out the extension point. But it would be much more useful if it didn't limit me to one interface.

#350 is only a start point on that subject (`Support any interface as an ExtensionPoint` - #289). It was simple from implementation point of view to allow only one interface for an extension (see the code [here](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/processor/ExtensionAnnotationProcessor.java#L212)).
Sure, we can add here a strategy pattern in `extensionAnnotationProcessor`, to allow you to define how the extension point/points is/are identified, something similar with `pf4j.storageClassName`.
It's only an idea. If anyone has a better idea (or simply another idea), I'm ready to discuss it.

> I'd also prefer to be able to define my own marker annotation in my app rather than having to use ExtensionPoint

You must understand that the approach with `ExtensionPoint` interface marker and `Extension` annotation is optional (it's only the default implemenation).
That was idea when I introduced [ExtensionFinder](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/ExtensionFinder.java).
For example, you can a look on [ServiceProviderExtensionFinder](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/ServiceProviderExtensionFinder.java), it's nothing here about `ExtensionPoint` interface.

> I just noticed Extension.points.
If this allowed me to specify my own interfaces (and even classes) to extend instead of having to supply a single interface it would work great. Unfortunately, it has to reference an ExtensionPoint. :(

See my explanation on https://github.com/pf4j/pf4j/issues/289#issuecomment-556436265. Maybe it's time to relax a little bit the type for `Extension#points` field.

> I don't understand the case for this to be multiple extension points defined.

This feature was introduced by #265. I don't know if @pinhead84 or other user has a concrete use case or not.

**Comment by pinhead84** [comment]
Hi claymccoy.

> > I don't understand the case for this to be multiple extension points defined.
> 
> This feature was introduced by #265. I don't know if @pinhead84 or other user has a concrete use case or not.

I've described my motivation about this feature and a little use case in #264. Basically an extension might not implement an `ExtensionPoint` directly. There might be one or more interfaces or abstract classes in between. In this case the `ExtensionAnnotationProcessor` might have some problems  detecting the correct `ExtensionPoint` interfaces for an extension at compile time.

To make life easier for the `ExtensionAnnotationProcessor`, the developer can explicitly configure all the `ExtensionPoint` interfaces, that are implemented by an extension, by putting their classes into the [Extension.points](https://github.com/pf4j/pf4j/blob/f6ebda434d51a6e9708e6612f422eb88420ff99d/pf4j/src/main/java/org/pf4j/Extension.java#L48) parameter.

Maybe I'm wrong, but I'm afraid that this feature won't help you regarding your feature request.

**Comment by claymccoy** [comment]
@pinhead84 
I totally understand the case for #264. What I was saying that I didn't understand was the need to define multiple points there. I'm pointing this out because with #350 where I can define any interface as an extension point, I am limited to only one interface. So these approaches seem inconsistent in that in one way I can only specify a single exension point and in the other it can be multiple.
Also, I really like Extension.points even though I asserting that maybe it should be Extension.point singlular. I wish that I could extend any interface (or class), by adding it there, rather than by having to put a single interface on my extension. Also, the type would need to be relaxed from ExtensionPoint.
As @decebals pointed out, I guess I can make my own ExtensionFinder that uses something like Extension.points to define my nonExtensionPoint  interface that is actually an extension point. I was just wondering what your thoughts were about this. Basically it seems like both #265 and #350 could be combined into a more consistent, less constrained way of specifying extension points even when they are not actually implementing ExtensionPoint.

**Comment by decebals** [comment]
I created a PR with some easy modifications that come to solve some issues discussed in this issue.

**Comment by decebals** [comment]
@claymccoy What to do with this issue and implicitly with #360, it is still relevant to you? 
If #360 solves your problem, I think that we can add it in [PF4J 4 roadmap](https://github.com/pf4j/pf4j/issues/372).

**Comment by decebals** [comment]
Close it due to lack of response. You can reopen it with a new comment.
