### ISSUE TITLE
pluginClassLoader.getResourceAsStream returns hosting app's resource when using spring boot app.jar deployment

### ISSUE THREAD

**Issue by cameronbraid** [pf4j/pf4j#409]
In dev I can call `pluginClassLoader.getResourceAsStream("git.json")` and it loads the file.json from the plugin jar, demonstrated with 

```
pluginClassLoader.getResource("file.json") ->
file:/tmp/drivenow-webapp.plugins.default.15696590027810601102/drivenow-webclients-SNAPSHOT/classes/git.json
```

however when I deploy my app using as app.jar I get file.json from the app.jar instead of the plugin jar, demonstrated with 

```
pluginClassLoader.getResource("git.json") ->
jar:file:/app/app.jar!/BOOT-INF/classes!/git.json
```

**Comment by decebals** [comment]
In `dev` mode the plugin storage is a directory.
In `deploy`(`prod`) mode the plugin storage is a JAR file. 
I encounter you problem in other projects when I tried (directly or indirectly) to materialize a `File` from an `URL`. In variant with `jar` (`zip`) I receive an error (NPE if I remember correctly).

I din't answer you until now because I see that you use Spring Boot and I didn't use PF4J with Spring Boot.

**Comment by decebals** [comment]
@cameronbraid Any resolution on this topic? Did you find a solution?

**Comment by decebals** [comment]
Close it due to lack of response. You can reopen it with a new comment.
