### ISSUE TITLE
Local plugin lifecycle

### ISSUE THREAD

**Issue by LovinLifee** [pf4j/pf4j#446]
I want to declare a plugin within the application jar but I need access to the plugins lifecycle ie start/stop functions, but plugin requires me to create a PluginWrapper which I assume is being done `magically` when you specify the meta data in the applications manifest. Is this possible to do or do I have to call the super classes constructor and explicitly create the PluginWrapper myself?

**Comment by decebals** [comment]
I don't understand your use case. It's not possible to have plugin(s) in the application jar. It's possible to have only extensions (points) and they are named system/default extensions (points). I don't understand why you cannot have each plugin located in a separate zip/jar file.

**Comment by LovinLifee** [comment]
Ah, that makes a lot more sense now. I absolutely can have each plugin in a separate file, it's just I would have liked to ship some default plugins with my application while keeping it tightly coupled to the project. It would make it a lot easier to maintain these plugins as I wouldn't have to create separate projects for each plugin because there's quite a few. Perhaps this could be a feature request.

**Comment by decebals** [comment]
> Ah, that makes a lot more sense now. I absolutely can have each plugin in a separate file, it's just I would have liked to ship some default plugins with my application while keeping it tightly coupled to the project. I

It's OK and probable common that your application to comes with some extensions and extensions points. I don't understand why you want to have plugins. Do you need some info about life cycle to do some initialization or what?

> t would make it a lot easier to maintain these plugins as I wouldn't have to create separate projects for each plugin because there's quite a few. Perhaps this could be a feature request.

It's not necessary  to create separate projects for each plugin, I use one multi module project for each application. In variant with multi modules (see demo) it's very easy to dev because it's not necessary to assemble the plugins (jar, zip). It's enough to run your main application class (the class that contains the main method). For more information see https://pf4j.org/doc/development-mode.html

**Comment by decebals** [comment]
@LovinLifee What is the status of this issue? Can we close it?
