### ISSUE TITLE
Can pf4j implement ClassLoader encryption?

### ISSUE THREAD

**Issue by fendo8888** [pf4j/pf4j#483]
I want to encrypt the class in the plug-in, and then decrypt the class through the ClassLoader method, that is, when the plug-in is loaded, I see that there is a JarPluginLoader in the source code, I customize a class according to this, I don't know if it can be achieved , do you have relevant experience or advice here?

**Comment by decebals** [comment]
It's not clear for me what you try to achieve.
Let's say that you have a plugin A. Do you want to encrypt all the classes from this package or what?
Can you you explain your use case?

**Comment by fendo8888** [comment]
Yes, I want to encrypt all the code in the plug-in and decrypt it by customizing the ClassLoader. In PF4J, I don't know if this can be done. In ordinary Java, inherit a ClassLoader and rewrite findClass to decrypt the class

**Comment by decebals** [comment]
I don't know what to say here. It's for the first time when I see a such request.
You can try.
You can use what `ClassLoader` you want in PF4J but I recommend you start from `PluginClassLoader` because it put some value on the table. I think that you don't want to obfuscate the class name (I see some problem here).
If you want to try an implementation, my advice is to start with a tiny Java project that (without PF4J) and after this try to apply same approach in a PF4J aware application. You can share with us your progress to help you.

**Comment by fendo8888** [comment]
This feature has been implemented, this issue can be closed

**Comment by decebals** [comment]
I would appreciate it if you could write a few words about your implementation. I think it would be useful for other users. Thanks!
And please close this issue yourself.
