### ISSUE TITLE
The plugin classloader is closed, but the classes in the JVM are not released

### ISSUE THREAD

**Issue by my-fastcms** [pf4j/pf4j#505]
spring holds a reference to a class in the plugin, which causes the class in the JVM not to be released after the plugin classloader is closed. What is a good solution

**Comment by decebals** [comment]
I know about this behavior. As far as I can tell, it only happens on Windows OS an it's normal somehow (it's not related PF4J or Spring).
PF4J delegates to Java core the part with loading bytes from files. I think that you can use a custom class loader (override `findClass` method and use a `Map<String, byte[]> resourceToBytes`). 
I am curios to know if you have the same behavior for a not Spring application.

**Comment by my-fastcms** [comment]
I see that in your web example, a new spring application will be created in the plug-in. Now I directly load the classes in the plug-in into the spring application. Now, there will be multiple classes loaded by the plugin classloader in the spring application

**Comment by decebals** [comment]
It's hard for me to follow you. I'm trying to somehow isolate the problem from Spring, maybe we can see a possible issue in PF4J. Spring is a huge ecosystem and it's hard to see all the implications. It will be great if you can create a [quickstart](https://pf4j.org/dev/quickstart.html) application that replicate the problem.

**Comment by my-fastcms** [comment]
From https://github.com/my-fastcms/fastcms.git Download the code,
Maven and MySQL need to be installed to run the project,
The SQL script is under the Doc / SQL directory of the project. You need to import the SQL script into the MySQL database,
Please run the testplugin method of testcaseservice in the test directory under the web module to find the problem

**Comment by my-fastcms** [comment]
Problem Description:

*After the plug-in is uninstalled and reinstalled, when the mapper is injected into the service, the problem that the mapper instance does not exist in the container will be reported

*

*Reason:

*Spring will compare the mapper loaded by the previous classloader with the mapper in the newly installed classloader of the plug-in

*It is reasonable that after the plug-in is unloaded, the classloader is also closed, but the TargetType of the root bean definition still holds the reference of the mapper class loaded by the previous classloader

*

*Solution:

*At present, the tentative solution is to manually set the value of TargetType with the mapper class loaded by the new classloader to forcibly replace the mapper class loaded by the old classloader

*Specific code reference

*{@ see generictypeawareautowirecenditeresolver # checkgenerictypematch()} line 98 of the method, you will find the old mapper class in the root definition

*Line 348 of {@ see resolvabletype # isassignablefrom()} method is used to compare whether mapper in bean definition is loaded by the same classloader

**Comment by decebals** [comment]
As I said in my previous comment please create a quickstart application or better yet a unit test that reproduces the problem. Try to formulate a problem related only to PF4J without other dependencies (Spring, ..). Time spent by me on this project is limited.

**Comment by decebals** [comment]
Can you add more details please?
Yes, it's a possibility that the same class to be loaded multiple times by different PluginClassLoader if this class is presented in two ore more plugins.

**Comment by finn0s** [comment]
## Problem
I have the same problem executing the following code.

<pre>
final JarPluginManager jarPluginManager = new JarPluginManager(Path.of(BASE));
jarPluginManager.loadPlugins();
jarPluginManager.startPlugins();
jarPluginManager.getExtensions(DummyExtension.class);
jarPluginManager.deletePlugin(jarPluginManager.getPlugins().get(0).getPluginId());
</pre>

The plugin project includes a <b>share</b> dependency with some dto classes.
The same <b>share</b> dependency is included in the main project.

The Programm works fine when compiling with the `maven-assembly-plugin` Plugin.
But when it's compiled with the `spring-boot-maven-plugin` Plugin the following exception is thrown.

``org.pf4j.PluginRuntimeException: java.nio.file.FileSystemException: [file]: The process cannot access the file because it is being used by another process.``

## Example
[example.zip](https://github.com/pf4j/pf4j/files/10897013/example.zip)
I have created a minimal example with three mvn modules(share, plugin and main).<br>
To build the main project with the `spring-boot-maven-plugin` Plugin run: <code>mvn clean install -Pwith-spring</code>
To build the main project with the `maven-assembly-plugin` Plugin run: <code>mvn clean install -Pwithout-spring</code>
### Important:
I'm using IntelliJ IDEA for development and when I start the application with IntelliJ, it works fine.
You have to run it via cli to reproduce the problem.

**Comment by decebals** [comment]
@finn0s Are you running the example on Windows? If the answer is yes, can you run it on other OS (Linux for example)?

**Comment by decebals** [comment]
@finn0s Can you post the entire stack trace and possibly a thread dump?

**Comment by decebals** [comment]
@finn0s How can I run your example from command line? Please supply all details if you want want to be helped.

**Comment by decebals** [comment]
> The Programm works fine when compiling with the maven-assembly-plugin Plugin.
But when it's compiled with the spring-boot-maven-plugin Plugin the following exception is thrown.

I don't understand here. As I mentioned in https://github.com/pf4j/pf4j/issues/505#issuecomment-1242952307 please isolate the problem. You say that only in the context of Spring you can replicate the problem and or a simple PF4J application (no Spring) everything runs as expected . Is it correct?

**Comment by finn0s** [comment]
As far as I can tell the problem only occurs if the programm is built with the `spring-boot-maven-plugin`.
The problem seems to be more severe under Windows, because Windows throws an error if an opened file is being deleted.

## Exception in Windows
### Exception
<pre>
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.pf4j.PluginRuntimeException: java.nio.file.FileSystemException: C:\Users\user\Desktop\example\Plugin\target\Plugin-1.0-SNAPSHOT.jar: The process cannot access the file because it is being used by another process
        at org.pf4j.BasePluginRepository.deletePluginPath(BasePluginRepository.java:93)
        at org.pf4j.CompoundPluginRepository.deletePluginPath(CompoundPluginRepository.java:71)
        at org.pf4j.AbstractPluginManager.deletePlugin(AbstractPluginManager.java:345)
        at org.example.Main.main(Main.java:17)
        ... 8 more
Caused by: java.nio.file.FileSystemException: C:\Users\user\Desktop\example\Plugin\target\Plugin-1.0-SNAPSHOT.jar: The process cannot access the file because it is being used by another process
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
        at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
        at java.base/java.nio.file.Files.delete(Files.java:1152)
        at org.pf4j.util.FileUtils$1.visitFile(FileUtils.java:93)
        at org.pf4j.util.FileUtils$1.visitFile(FileUtils.java:88)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2811)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
        at org.pf4j.util.FileUtils.delete(FileUtils.java:88)
        at org.pf4j.BasePluginRepository.deletePluginPath(BasePluginRepository.java:88)
        ... 11 more
</pre>

### Thread dump
[thread_dump.txt](https://github.com/pf4j/pf4j/files/10908543/thread_dump.txt)

## How to reproduce under linux
### Build and run the application
To run the application with the `spring-boot-maven-plugin` execute the following commands in the example folder:
<pre>
mvn clean install -Pwith-spring
java -jar Main/target/Main-1.0-SNAPSHOT.jar
</pre>

### How to diagnose the problem (under linux)
When I run the program under linux it doesn't throw an exception. But it also doesn't release the file handle until the program is terminated.
In my example the program exits immediately after deleting the file.
I updated the example to not exit immediately. You now have to kill the program with ^C after you are done.
[new_example.zip](https://github.com/pf4j/pf4j/files/10908535/example.zip)

You can see that the file is still opened if you list the file descriptors that the java process has opened.
You first have to get the pid: `ps -C java -o pid=`

And then list the file descriptors using the following command: `ls -l /proc/{pid}/fd`.
With the `spring-boot-maven-plugin` I get the following output:
<pre>
osboxes@osboxes:~/Desktop/example$ ls -l /proc/2465/fd
total 0
lrwx------ 1 osboxes osboxes 64 Mar  7 04:33 0 -> /dev/pts/0
lrwx------ 1 osboxes osboxes 64 Mar  7 04:33 1 -> /dev/pts/0
lrwx------ 1 osboxes osboxes 64 Mar  7 04:33 2 -> /dev/pts/0
lr-x------ 1 osboxes osboxes 64 Mar  7 04:33 3 -> /usr/lib/jvm/java-17-openjdk-amd64/lib/modules
lr-x------ 1 osboxes osboxes 64 Mar  7 04:33 4 -> /home/osboxes/Desktop/example/Main/target/Main-1.0-SNAPSHOT.jar
lr-x------ 1 osboxes osboxes 64 Mar  7 04:33 5 -> /home/osboxes/Desktop/example/Main/target/Main-1.0-SNAPSHOT.jar
lr-x------ 1 osboxes osboxes 64 Mar  7 04:33 7 -> '/home/osboxes/Desktop/example/Plugin/target/Plugin-1.0-SNAPSHOT.jar (deleted)'
</pre>

The last line indicates that the Plugin jar file is flagged for deletion but still opened. The file will be deleted after the main program terminates.

Without the `spring-boot-maven-plugin` the file gets deleted and won't stay opened as seen below.
<pre>
osboxes@osboxes:~/Desktop/example$ ls -l /proc/2719/fd
total 0
lrwx------ 1 osboxes osboxes 64 Mar  7 04:45 0 -> /dev/pts/0
lrwx------ 1 osboxes osboxes 64 Mar  7 04:45 1 -> /dev/pts/0
lrwx------ 1 osboxes osboxes 64 Mar  7 04:45 2 -> /dev/pts/0
lr-x------ 1 osboxes osboxes 64 Mar  7 04:45 3 -> /usr/lib/jvm/java-17-openjdk-amd64/lib/modules
lr-x------ 1 osboxes osboxes 64 Mar  7 04:45 4 -> /home/osboxes/Desktop/example/Main/target/Main-1.0-SNAPSHOT.jar
</pre>

**Comment by decebals** [comment]
Thanks for detailed description. 
If you have some available time, please try to run with PF4J version available in `file_to_path` branch (see https://github.com/pf4j/pf4j/pull/486). I made some modifications in that branch, that may help.

**Comment by finn0s** [comment]
I ran the program with the `file_to_path` branch but didn't fix the problem.

When the program is compiled with the `spring-boot-maven-plugin` the program's entry point changes and spring sets a new classloader (`LaunchedURLClassLoader`). The problem has somethig to do with this mechanism.

**Comment by decebals** [comment]
> When the program is compiled with the spring-boot-maven-plugin the program's entry point changes and spring sets a new classloader (LaunchedURLClassLoader). The problem has somethig to do with this mechanism.

Unfortunately I'm not a connoisseur of Spring mechanisms, maybe other PF4J user that uses PF4J in combination with Spring Boot can help. Put a question on https://github.com/hank-cp/sbp, can help.

If you isolate the problem (only PF4J with no Spring), I will try my best to help.

**Comment by decebals** [comment]
@finn0s says his problem has been solved (for more details see #519) and that the issue can be closed from his point of view.
@my-fastcms what is the status on your side?

**Comment by decebals** [comment]
Please reopen the issue if you need more help.
