### ISSUE TITLE
Question: How to add extension point from another plugin for another plugin?

### ISSUE THREAD

**Issue by duruer** [pf4j/pf4j#554]
Hi, sorry for opening issue for this question but I couldn't find any solution to this.

I have 2 plugins: Auth and Database
Auth is depended on Database. So I try to make an extension point from database to Auth because I wanna Listen when real database tables are prepared by database plugin.

How can I do this?

**Comment by decebals** [comment]
I'm not sure that I understand your question.
So you have Database plugin (P1) and Auth plugin (P2), P2 idepends on P1 (you need to specify this in the plugin descriptor pf P2).
Now, in P2 you declare an extension point (EP) - your Listener, and in P1 you declare an extension (E) of EP.
Probably your problem is that in P1 you cannot retrieve all extensions of EP (Listener).
This is information is available via [PluginManager#getExtensions](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/PluginManager.java#L152).
It's your responsibility (application creator) to pass this information to plugin via PluginContext. Your PluginContext can be an interface passed to plugin(s), with one method `getExtensions(Class<T> type):List<T>` and the implementation of this method delegates to `pluginManager.getExtensions` (method with the same signature).

See https://github.com/pf4j/pf4j/issues/319,  https://github.com/pf4j/pf4j/issues/187 and https://github.com/pf4j/pf4j/issues/530 for more details.

Does what I'm saying make sense to you?

**Comment by decebals** [comment]
@duruer Need more hep? Can we close this issue?

**Comment by duruer** [comment]
Hi, I apologize for the late reply. Yes, it is helpful I'm closing the issue. Thank you.
